// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVFuhagACPijl9Zx7paFO00fe4L7bruSQ',
    appId: '1:682576760847:web:de02c6474c043d1561137a',
    messagingSenderId: '682576760847',
    projectId: 'login-with--task-437de',
    authDomain: 'login-with--task-437de.firebaseapp.com',
    storageBucket: 'login-with--task-437de.appspot.com',
    measurementId: 'G-VFQ7XZDGKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwj65MUMYkdcvTYMO-lfoIk18vAErs6Wg',
    appId: '1:682576760847:android:d23dec2e5a6c36f661137a',
    messagingSenderId: '682576760847',
    projectId: 'login-with--task-437de',
    storageBucket: 'login-with--task-437de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOafPw7X5et9fVPZZrPAS0lYwZun570hQ',
    appId: '1:682576760847:ios:134cc16a1f833a3b61137a',
    messagingSenderId: '682576760847',
    projectId: 'login-with--task-437de',
    storageBucket: 'login-with--task-437de.appspot.com',
    iosClientId: '682576760847-gaaarmm2jhkt71s3n13kfamrcui5smd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginWithGoogleTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOafPw7X5et9fVPZZrPAS0lYwZun570hQ',
    appId: '1:682576760847:ios:3488c1014590473f61137a',
    messagingSenderId: '682576760847',
    projectId: 'login-with--task-437de',
    storageBucket: 'login-with--task-437de.appspot.com',
    iosClientId: '682576760847-7dk33rhuhmp7o33b5knt8jbe3ntlq13a.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginWithGoogleTask.RunnerTests',
  );
}
